### PR TITLE
Docker image

### PR DESCRIPTION
**Pull request by heywoodlh**
README.md contains the instructions for building the image.

However, at the moment, it does not quite work for me and I don't think this PR should be merged until it is fixed. While in the container I try to run the following:

```
echo 'blah' > /data/Notes/test.md
```

Which results in this error:

```
4/13/2022, 11:32:41 PM->Detected:created:/data/Notes/test.md
4/13/2022, 11:32:41 PM->save ok:id:h:+58e1d0ea rev:1-e205e6d984080f9e795fe12b3abd9342
4/13/2022, 11:32:41 PM->note content saven, pieces:1 new:1, skip:0, cache:0
4/13/2022, 11:32:41 PM->note saved:undefinedtest.md:1-9e8722396d9c3b5bf91c29275a1d9681
4/13/2022, 11:32:41 PM->doc:config_1: undefinedtest.md (1-9e8722396d9c3b5bf91c29275a1d9681) begin Transfer
4/13/2022, 11:32:41 PM->Exception on transfer doc
4/13/2022, 11:32:41 PM->TypeError:Cannot read properties of undefined (reading 'length')
```

Any suggestions there?

Also in the configuration file what is the difference between `server.path` and `local.path`?

### CODE REVIEW

**Comment by vrtmrz** [comment]
Sorry, maybe it's a too simple reply. it is from mobile. 

- Local vault’s path should be relative and subfolder from this app
- Remote path can be empty in this sample.

But folder limitations should be solved to run on the docker... Thank you for your review!

**Comment by heywoodlh** [comment]
Can the local reflect a full path? Or does it have to be relative?

**Comment by vrtmrz** [comment]
Each file’s path should be resolved as relative path from the folder that set in the configure.
But, referring to the log, it doesn't.
We have to make this logic sure. 
(maybe around https://github.com/vrtmrz/filesystem-livesync/blob/5d937a68b129e6085f5f623b709d829e49297b03/src/index.ts#L340)

**Comment by heywoodlh** [comment]
So I feel like this is ready to merge.

Please let me know if you need anything else from me before you want to merge.

**Comment by vrtmrz** [comment]
Sorry for being late! 
I am very honored and happy to receive this contribution from you! I'm very thank you again.

**Comment by hilsonp** [comment]
Hello @heywoodlh,

Is the heywoodlh/filesystem-livesync maintained ?
Do you plan to continue maintaining it when @vrtmrz publishes updates ?

Hello @vrtmrz,

If this is maintained, I think it would be worth noting it in the README.md.
Would you need help describing the setup using docker-compose ?

Thank you both,

Pierre

**Pull request merged**
